workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          cd pads_sampler
          flutter pub get

      - name: Build APK
        script: |
          cd pads_sampler
          flutter build apk --release
    artifacts:
      - pads_sampler/build/app/outputs/flutter-apk/app-release.apk
